
ConsolePortBarManifest = {
	["ReticleSpells"] = {
		["DEATHKNIGHT"] = {
			[49936] = "Death and Decay",
			[49938] = "Death and Decay",
			[43265] = "Death and Decay",
			[49937] = "Death and Decay",
		},
		["WARLOCK"] = {
			[11667] = "Immolate",
			[11678] = "Rain of Fire",
			[5740] = "Rain of Fire",
			[27212] = "Rain of Fire",
			[6219] = "Rain of Fire",
			[47820] = "Rain of Fire",
			[47819] = "Rain of Fire",
		},
		["MAGE"] = {
			[27085] = "Blizzard",
			[10216] = "Flamestrike",
			[8423] = "Flamestrike",
			[27086] = "Flamestrike",
			[10215] = "Flamestrike",
			[6141] = "Blizzard",
			[10] = "Blizzard",
			[10185] = "Blizzard",
			[42940] = "Blizzard",
			[2120] = "Flamestrike",
			[8422] = "Flamestrike",
			[2121] = "Flamestrike",
			[42925] = "Flamestrike",
			[8427] = "Blizzard",
			[10187] = "Blizzard",
		},
		["DRUID"] = {
			[27012] = "Hurricane",
			[17402] = "Hurricane",
			[16914] = "Hurricane",
			[48467] = "Hurricane",
			[17401] = "Hurricane",
			[33831] = "Force of Nature",
		},
		["HUNTER"] = {
			[14925] = "Growl",
			[27022] = "Volley",
			[58431] = "Volley",
			[1510] = "Volley",
			[60192] = "Freezing Arrow",
			[14294] = "Volley",
			[1543] = "Flare",
			[58434] = "Volley",
		},
	},
	["BindingIcons"] = {
		["TARGETNEARESTENEMYPLAYER"] = "Interface\\AddOns\\ConsolePortBar\\Textures\\Icons\\Target",
		["TARGETNEARESTENEMY"] = "Interface\\AddOns\\ConsolePortBar\\Textures\\Icons\\Target",
		["TARGETPARTYMEMBER2"] = "Interface\\Icons\\Achievement_PVP_A_02",
		["CLICK ConsolePortFocusButton:LeftButton"] = "Interface\\Icons\\VAS_RaceChange",
		["CLICK ConsolePortRaidCursorFocus:LeftButton"] = "Interface\\AddOns\\ConsolePortBar\\Textures\\Icons\\Group",
		["TARGETPARTYMEMBER1"] = "Interface\\Icons\\Achievement_PVP_A_01",
		["TOGGLEGAMEMENU"] = "Interface\\AddOns\\ConsolePortBar\\Textures\\Icons\\Menu",
		["TARGETSCANENEMY"] = "Interface\\AddOns\\ConsolePortBar\\Textures\\Icons\\Target",
		["TARGETNEARESTFRIEND"] = "Interface\\AddOns\\ConsolePortBar\\Textures\\Icons\\Target",
		["JUMP"] = "Interface\\AddOns\\ConsolePortBar\\Textures\\Icons\\Jump",
		["ATTACKTARGET"] = "Interface\\Icons\\Ability_SteelMelee",
		["CLICK ConsolePortRaidCursorTarget:LeftButton"] = "Interface\\AddOns\\ConsolePortBar\\Textures\\Icons\\Group",
		["TARGETNEARESTFRIENDPLAYER"] = "Interface\\AddOns\\ConsolePortBar\\Textures\\Icons\\Target",
		["TARGETSELF"] = "Interface\\Icons\\Achievement_PVP_A_05",
		["CLICK ConsolePortTotemToggle:LeftButton"] = "Interface\\AddOns\\ConsolePort\\Textures\\Icons\\Totems",
		["STARTATTACK"] = "Interface\\Icons\\Ability_SteelMelee",
		["CLICK ConsolePortRaidCursorToggle:LeftButton"] = "Interface\\AddOns\\ConsolePortBar\\Textures\\Icons\\Group",
		["TARGETPREVIOUSFRIENDPLAYER"] = "Interface\\AddOns\\ConsolePortBar\\Textures\\Icons\\Target",
		["TARGETPREVIOUSENEMY"] = "Interface\\AddOns\\ConsolePortBar\\Textures\\Icons\\Target",
		["CLICK ConsolePortEasyMotionButton:LeftButton"] = "Interface\\AddOns\\ConsolePortBar\\Textures\\Icons\\Group",
		["FOCUSTARGET"] = "Interface\\Icons\\Ability_Hunter_MasterMarksman",
		["TOGGLEWORLDMAP"] = "Interface\\AddOns\\ConsolePortBar\\Textures\\Icons\\Map",
		["PETATTACK"] = "Interface\\Icons\\ABILITY_HUNTER_INVIGERATION",
		["TARGETPARTYMEMBER4"] = "Interface\\Icons\\Achievement_PVP_A_04",
		["OPENALLBAGS"] = "Interface\\AddOns\\ConsolePortBar\\Textures\\Icons\\Bags",
		["TARGETPET"] = "Interface\\Icons\\Spell_Hunter_AspectOfTheHawk",
		["CLICK ConsolePortUtilityToggle:LeftButton"] = "Interface\\AddOns\\ConsolePortBar\\Textures\\Icons\\Ring",
		["TARGETPREVIOUSFRIEND"] = "Interface\\AddOns\\ConsolePortBar\\Textures\\Icons\\Target",
		["TARGETPREVIOUSENEMYPLAYER"] = "Interface\\AddOns\\ConsolePortBar\\Textures\\Icons\\Target",
		["TOGGLERUN"] = "Interface\\AddOns\\ConsolePortBar\\Textures\\Icons\\Run",
		["TARGETPARTYMEMBER3"] = "Interface\\Icons\\Achievement_PVP_A_03",
	},
}
