/**
 * Typed wrapper + helpers around the parsed talent-builds dataset.
 *
 * The raw JSON is generated by the Rust dataset builder
 * (src-tauri/src/talent_dataset.rs) from mod-playerbots'
 * playerbots.conf.dist `PremadeSpecName` / `PremadeSpecLink` entries.
 *
 * Consumers (currently just the Add-to-Party wizard) should import
 * helpers from this module rather than touching the JSON directly —
 * this keeps the schema and the role-inference rules in one place.
 */
import datasetJson from "@/lib/talent-builds.json"

export type Role = "Tank" | "Healer" | "DPS"
export const ALL_ROLES: Role[] = ["Tank", "Healer", "DPS"]

export interface TalentRow {
  spell: number
  specMask: number
  tabIndex: number
  tier: number
  column: number
  rank: number
}

export interface TalentBuild {
  level: number
  wowheadLink: string
  totalPoints: number
  treeDistribution: [number, number, number]
  primaryTab: number
  talents: TalentRow[]
}

export interface SpecEntry {
  classId: number
  specIndex: number
  /** Lowercased mod-playerbots spec name (e.g. "arms pve", "holy pvp"). */
  specName: string
  builds: TalentBuild[]
}

export interface TalentDataset {
  version: number
  sourceFile: string
  extractedAt: string
  specCount: number
  buildCount: number
  specs: SpecEntry[]
}

export const dataset = datasetJson as TalentDataset

/**
 * Tag a spec as Tank / Healer / DPS based on its name + class id.
 *
 * Rationale: mod-playerbots' conf spec names don't carry an explicit
 * "role" field, but the canonical WotLK class/spec → role mapping is
 * unambiguous for every spec the conf ships. We hardcode the rules
 * for the four classes that have non-DPS specs (warr/pally/DK/druid
 * for tanks, pally/priest/shaman/druid for healers) and default
 * everything else to DPS.
 */
export function inferRole(classId: number, specName: string): Role {
  const s = specName.toLowerCase()

  // Tank specs
  if (classId === 1 && s.startsWith("prot")) return "Tank" // Warrior
  if (classId === 2 && s.startsWith("prot")) return "Tank" // Paladin
  if (classId === 6 && s.includes("blood")) return "Tank" // Death Knight (WotLK)
  if (classId === 11 && s.startsWith("bear")) return "Tank" // Druid

  // Healer specs
  if (classId === 2 && s.startsWith("holy")) return "Healer" // Paladin
  if (classId === 5 && (s.startsWith("holy") || s.startsWith("disc")))
    return "Healer" // Priest
  if (classId === 7 && s.startsWith("resto")) return "Healer" // Shaman
  if (classId === 11 && s.startsWith("resto")) return "Healer" // Druid

  return "DPS"
}

/** Class ids that have at least one spec matching the given role. */
export function getClassesForRole(role: Role): number[] {
  const seen = new Set<number>()
  for (const spec of dataset.specs) {
    if (inferRole(spec.classId, spec.specName) === role) {
      seen.add(spec.classId)
    }
  }
  return [...seen].sort((a, b) => a - b)
}

/** Specs for a (class, role) pair, returned in deterministic order. */
export function getSpecsForClassRole(
  classId: number,
  role: Role
): SpecEntry[] {
  return dataset.specs
    .filter(
      (s) =>
        s.classId === classId && inferRole(s.classId, s.specName) === role
    )
    .sort((a, b) => a.specIndex - b.specIndex)
}

/** Build levels available for a spec, sorted ascending. */
export function getBuildLevels(spec: SpecEntry): number[] {
  return spec.builds.map((b) => b.level).sort((a, b) => a - b)
}

/** Pick the build at a specific level, or null if not present. */
export function getBuildAtLevel(
  spec: SpecEntry,
  level: number
): TalentBuild | null {
  return spec.builds.find((b) => b.level === level) ?? null
}

/**
 * Snap a target level to the nearest build level for a spec.
 * Used so a character level of 73 surfaces the level-70 build
 * (which is the highest build ≤ 73) by default in the wizard.
 */
export function snapToBuildLevel(
  spec: SpecEntry,
  targetLevel: number
): number | null {
  const levels = getBuildLevels(spec)
  if (levels.length === 0) return null
  let best: number | null = null
  for (const lvl of levels) {
    if (lvl <= targetLevel) best = lvl
  }
  // If targetLevel is below the lowest build, fall back to that lowest one.
  return best ?? levels[0]
}

/**
 * Pretty-print a conf spec name for UI display.
 *
 *   "arms pve"           → "Arms (PvE)"
 *   "bm pve"             → "Beast Mastery (PvE)"
 *   "double aura blood pve" → "Double Aura Blood (PvE)"
 */
const SPEC_WORD_EXPANSIONS: Record<string, string> = {
  // mod-playerbots short codes → human names
  as: "Assassination",
  bm: "Beast Mastery",
  mm: "Marksmanship",
  surv: "Survival",
  disc: "Discipline",
  affli: "Affliction",
  demo: "Demonology",
  destro: "Destruction",
  ele: "Elemental",
  enh: "Enhancement",
  resto: "Restoration",
  ret: "Retribution",
  prot: "Protection",
  subtlety: "Subtlety",
  frostfire: "Frostfire",
  // Mode tags
  pve: "(PvE)",
  pvp: "(PvP)",
}

export function formatSpecName(raw: string): string {
  const tokens = raw.toLowerCase().split(/\s+/)
  const out: string[] = []
  for (const token of tokens) {
    if (token in SPEC_WORD_EXPANSIONS) {
      out.push(SPEC_WORD_EXPANSIONS[token])
    } else {
      out.push(token.charAt(0).toUpperCase() + token.slice(1))
    }
  }
  // The mode tag (PvE/PvP) is always last; the join already places
  // it correctly. Trim any double spaces around the parenthesized tag.
  return out.join(" ").replace(/\s+\(/, " (")
}
